# Generated by Django 4.2.21 on 2026-05-17 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_ensure_foundation_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                ("registration_open_date", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_close_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("registration_open", "Registration Open"),
                            ("registration_closed", "Registration Closed"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("visible_to_students", models.BooleanField(default=False)),
                ("is_registration_open", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("allowed_years", models.JSONField(blank=True, default=list)),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to="quiz_banners/"),
                ),
                ("rules_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_branches",
                    models.ManyToManyField(blank=True, to="users.branch"),
                ),
                (
                    "allowed_programs",
                    models.ManyToManyField(blank=True, to="users.program"),
                ),
                (
                    "allowed_schools",
                    models.ManyToManyField(blank=True, to="users.school"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sequence_number", models.IntegerField(blank=True, null=True)),
                ("player_id", models.CharField(blank=True, max_length=40)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="quizregistration",
            constraint=models.UniqueConstraint(
                fields=("student", "quiz"), name="unique_student_registration_per_quiz"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizregistration",
            constraint=models.UniqueConstraint(
                fields=("quiz", "sequence_number"), name="unique_sequence_per_quiz"
            ),
        ),
    ]
