# Generated by Django 6.0.3 on 2026-05-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('regular', 'Regular (Preliminary)'), ('fff_1', 'Fastest Finger First (Batch 1)'), ('fff_2', 'Fastest Finger First (Batch 2)'), ('fff_3', 'Fastest Finger First (Batch 3)'), ('hotseat_1', 'Hotseat (Batch 1)'), ('hotseat_2', 'Hotseat (Batch 2)'), ('hotseat_3', 'Hotseat (Batch 3)')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='batch_1_players',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='batch_2_players',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='batch_3_players',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='current_stage',
            field=models.CharField(choices=[('regular', 'Regular Preliminary Quiz'), ('batch_selection', 'Selecting Top 30 and Batches'), ('fff_batch_1', 'Fastest Finger First - Batch 1'), ('hotseat_batch_1', 'Hotseat - Batch 1'), ('fff_batch_2', 'Fastest Finger First - Batch 2'), ('hotseat_batch_2', 'Hotseat - Batch 2'), ('fff_batch_3', 'Fastest Finger First - Batch 3'), ('hotseat_batch_3', 'Hotseat - Batch 3'), ('completed', 'Event Completed')], default='regular', max_length=40),
        ),
        migrations.AddField(
            model_name='quiz',
            name='event_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotseat_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotseat_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotseat_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_score_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_status_1',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_status_2',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hotseat_status_3',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='top_30_selected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='FFFAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fff_answers', to='quizzes.quiz')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fff_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quiz', 'student', 'batch_number', 'question'), name='unique_fff_answer')],
            },
        ),
        migrations.CreateModel(
            name='HotseatAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('current_question_index', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('walked_away', 'Walked Away'), ('failed', 'Failed'), ('completed', 'Completed')], default='playing', max_length=20)),
                ('lifeline_5050_used', models.BooleanField(default=False)),
                ('lifeline_poll_used', models.BooleanField(default=False)),
                ('lifeline_switch_used', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotseat_attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotseat_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quiz', 'student', 'batch_number'), name='unique_hotseat_attempt')],
            },
        ),
    ]
