# Generated by Django 6.0.3 on 2026-05-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_category_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='trivia',
            field=models.TextField(blank=True, default='', help_text='Trivia/fun facts related to the question'),
        ),
    ]
