# Generated by Django 6.0.3 on 2026-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_trivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_order',
            field=models.IntegerField(blank=True, help_text='1-indexed position in correct sequence (e.g., 1, 2, 3...)', null=True),
        ),
    ]
