# Generated by Django 6.0.3 on 2026-05-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_choice_correct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fffanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fffanswer',
            name='submitted_sequence',
            field=models.TextField(blank=True, default='', help_text='Comma-separated choice IDs in ordered sequence'),
        ),
    ]
