# Generated by Django 6.0.3 on 2026-05-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_fffanswer_is_correct_fffanswer_submitted_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='preselected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotseat_preselections', to='quizzes.choice'),
        ),
    ]
