# Generated by Django 6.0.3 on 2026-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_hotseatattempt_preselected_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='approved_lifeline_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hotseatattempt',
            name='lifeline_request_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='hotseatattempt',
            name='pending_lifeline_switch_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hotseatattempt',
            name='pending_lifeline_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
