# Generated by Django 6.0.3 on 2026-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_hotseatattempt_approved_lifeline_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='options_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotseatattempt',
            name='showing_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotseatattempt',
            name='timer_is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
