# Generated by Django 4.2.21 on 2026-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_hotseatattempt_options_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='show_intro',
            field=models.BooleanField(default=False),
        ),
    ]
