# Generated by Django 4.2.21 on 2026-05-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_hotseatattempt_show_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='current_question_switched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('regular', 'Regular (Preliminary)'), ('fff_1', 'Fastest Finger First (Batch 1)'), ('fff_2', 'Fastest Finger First (Batch 2)'), ('fff_3', 'Fastest Finger First (Batch 3)'), ('hotseat_1', 'Hotseat (Batch 1)'), ('hotseat_2', 'Hotseat (Batch 2)'), ('hotseat_3', 'Hotseat (Batch 3)'), ('switch', 'Switch Question')], default='regular', max_length=20),
        ),
        migrations.CreateModel(
            name='SwitchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='switch_categories/')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_category_link', to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_categories', to='quizzes.quiz')),
            ],
        ),
    ]
