# Generated by Django 6.0.3 on 2026-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_hotseatattempt_current_question_switched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim_mcq_timer', models.IntegerField(default=90)),
                ('fff_speed_timer', models.IntegerField(default=20)),
                ('hotseat_q1_q5_limit', models.IntegerField(default=60)),
                ('hotseat_q6_q10_limit', models.IntegerField(default=120)),
                ('auto_approve_registrations', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Preferences',
                'verbose_name_plural': 'System Preferences',
            },
        ),
    ]
