# Generated by Django 6.0.3 on 2026-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_systempreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='intro_played',
            field=models.BooleanField(default=False),
        ),
    ]
