# Generated by Django 6.0.3 on 2026-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_hotseatattempt_intro_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='intro_title',
            field=models.CharField(blank=True, default='Kaun Banega Codepati', max_length=200),
        ),
    ]
