# Generated by Django 4.2.21 on 2026-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_spectatorpollvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizregistration',
            name='arena_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
