# Generated by Django 4.2.21 on 2026-05-15 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("college_id", models.CharField(max_length=40, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("school", models.CharField(max_length=40)),
                ("branch", models.CharField(max_length=80)),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("1", "1st Year"),
                            ("2", "2nd Year"),
                            ("3", "3rd Year"),
                            ("4", "4th Year"),
                        ],
                        max_length=1,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "session_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
